project/avia_reis/urls.py
from django.contrib import admin
from django.urls import path

from avia_base.buy_ticket.views import (
    AviaSearch,
    api_avia_data,
    buy_ticket,
    AviaList,
    delete_ticket,
    RootList
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', AviaSearch.as_view()),
    path('list_reis/', api_avia_data),
    path('buy_ticket/', buy_ticket),
    path('list_buy_ticket/delete_ticket/', delete_ticket),
    path('list_buy_ticket/', AviaList.as_view(), name='list_ticket'),
    path('root/', RootList.as_view(), name='root'),
]

project/avia_base/buy_ticket/models.py
from django.db import models


class Ticket(models.Model):
    from_is_time = models.CharField(max_length=30)
    from_is = models.CharField(max_length=30)
    duration = models.CharField(max_length=30)
    where_is_time = models.CharField(max_length=30)
    where = models.CharField(max_length=30)

    back_from_is_time = models.CharField(max_length=30)
    back_from_is = models.CharField(max_length=30)
    back_duration = models.CharField(max_length=30)
    back_where_is_time = models.CharField(max_length=30)
    back_where = models.CharField(max_length=30)

project/avia_base/buy_ticket/views.py
from django.http import JsonResponse
from django.template.response import SimpleTemplateResponse
from django.views.generic import FormView, ListView

from avia_base.avia_api import action_with_data
from avia_base.buy_ticket.form import AviaFormSearch
from avia_base.buy_ticket.models import Ticket


class AviaSearch(FormView):
    template_name = 'avia/search.html'
    form_class = AviaFormSearch
    success_url = '/list'


def buy_ticket(
    form_data,
):
    del_list = ['Туда', 'Обратно', 'Купить', 'Продолжительность']
    create_list = [
        'from_is_time',
        'from_is',
        'duration',
        'where_is_time',
        'where',

        'back_from_is_time',
        'back_from_is',
        'back_duration',
        'back_where_is_time',
        'back_where',
    ]
    i = 0
    clean_list_data = []
    form_data = form_data.GET
    for data in form_data:
        if form_data[data] not in del_list:
            clean_list_data.append(
                {
                    create_list[i]: form_data[data].strip()
                }
            )
            i += 1
    ticket = Ticket.objects.create(
                from_is_time=clean_list_data[0]['from_is_time'],
                from_is=clean_list_data[1]['from_is'],
                duration=clean_list_data[2]['duration'],
                where_is_time=clean_list_data[3]['where_is_time'],
                where=clean_list_data[4]['where'],

                back_from_is_time=clean_list_data[5]['back_from_is_time'],
                back_from_is=clean_list_data[6]['back_from_is'],
                back_duration=clean_list_data[7]['back_duration'],
                back_where_is_time=clean_list_data[8]['back_where_is_time'],
                back_where=clean_list_data[9]['back_where'],
        )
    return JsonResponse(ticket.id, safe=False)


def delete_ticket(form):
    pk = form.GET['id']
    Ticket.objects.get(pk=pk).delete()
    id = pk
    return JsonResponse(id, safe=False)


def api_avia_data(request):
    from_is = request.GET['from_is']
    where = request.GET['where']
    when = request.GET['when']
    back = request.GET['back']
    passengers = request.GET['passengers']
    classe = request.GET['classe']

    response_data = {
        'results': action_with_data(from_is, where, when, back, passengers, classe)
    }

    if not response_data['results']:
        response_data = {
            'results': {
                'error': 'К сожелению авибилеты не найдены'
            }
        }

    obj_template = SimpleTemplateResponse(
        template='avia/list.html',
        context=response_data
    )

    template = obj_template.resolve_template(obj_template.template_name)
    context = obj_template.resolve_context(obj_template.context_data)
    html = template.render(context, obj_template._request)

    return JsonResponse(html, safe=False)


class AviaList(ListView):
    model = Ticket


class RootList(FormView):
    template_name = 'avia/scoreboard.html'
    form_class = AviaFormSearch
    success_url = '/root'

project/templates/avia/list.html
 <div class="container-fluid d-flex justify-content-center align-items-center">
        <div class="bg-white shadow-sm" style="border-radius: 5px">
           <div class="col p-3" style="background: #F3F3F3; border-radius: 5px">
            <h3 class="text-center mb-4" style="margin-bottom: 10px;">Результат</h3>
           {% if results.error %}
               {{ results.error }}
           {% else %}
                {% for element in results %}
                    <div class="form-group form-row" style="margin: 30px;" id="{{ element.id }}">


                                <h5 style="margin-top: -40px;; margin-right: -40px;">Туда</h5>
                                    <div class="form-group">
                                        <div class="form-control">{{ element.from_is_time }}</div>
                                        <div class="form-control">{{ element.from_is }}</div>
                                    </div>

                                    <div class="form-group" style="text-align: center">
                                         <div style="padding: 5px;">Продолжительность</div>
                                         <div style="padding: 5px;">{{ element.duration }}</div>
                                    </div>

                                    <div class="form-group">
                                        <div class="form-control">{{ element.where_is_time }}</div>
                                        <div class="form-control">{{ element.where }}</div>
                                    </div>



                                    <h5 style="margin-top: -36px;
                                    margin-left: 120px;
                                    margin-right: -81px;">Обратно</h5>
                                <div class="form-group">
                                        <div class="form-control">{{ element.back_from_is_time }}</div>
                                        <div class="form-control">{{ element.back_from_is }}</div>
                                    </div>

                                    <div class="form-group" style="text-align: center">
                                         <div style="padding: 5px;">Продолжительность</div>
                                         <div style="padding: 5px;">{{ element.back_duration }}</div>
                                    </div>

                                    <div class="form-group">
                                        <div class="form-control">{{ element.back_where_is_time }}</div>
                                        <div class="form-control">{{ element.back_where }}</div>
                                    </div>


                                        <div class="form-group">
                                        <button type="submit" class="btn btn-warning" id="{{ element.btn }}"
                                             style="margin-top: 16px;
                                             margin-left: 20px;">Купить</button>
                                                    </div>
                    </div>
                    <hr>
               {% endfor %}
           {% endif %}
           </div>
        </div>
    </div>

project/templates/avia/scoreboard.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
            integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
            crossorigin="anonymous"
    >

    <title>avia-reis</title>

    <style>
        html, body {
            height: 100%;
        }
        body {
            background-color: #6EA1FF;
        }
        p{
            padding: 7px;
        }
        .nav-tabs .nav-link {
            border: 0;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }
        .form-group {
            margin-bottom: 6rem;
        }
        .mb-4, .my-4 {
            margin-bottom: 6.5rem!important;
        }
         hr {
            border: none; /* Убираем границу */
            background-color: #5C5C5C; /* Цвет линии */
            color: #5C5C5C; /* Цвет линии для IE6-7 */
            height: 2px;
            margin-bottom: 120px;
           }
    </style>
  </head>
  <body>


    <ul class="nav nav-tabs d-flex justify-content-center align-items-center" style="background: white">
          <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/root/">Главная</a>
          </li>
          <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/">Поиск авиобилетов</a>
          </li>
          <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/list_buy_ticket/">Мои авиобилеты</a>
          </li>
    </ul>

   <div class="container-fluid d-flex justify-content-center align-items-center">
        <div class="bg-white shadow-sm" style="border-radius: 5px; margin-top: 100px;">
           <div class="col p-3" style="background: #F3F3F3; border-radius: 5px">
            <h3 class="text-center mb-4" style="margin-bottom: 10px;">Аэропорт Чебоксары онлайн табло вылета и прилета на сегодня</h3>
           {% if not ticket_list.count %}
              <p style="text-align: center"> У вас нет билетов</p>
           {% else %}
                {% for element in ticket_list %}
                    <div class="form-group form-row" style="margin: 30px;" id="{{ element.id }}">


                                <h5 style="margin-top: -40px;; margin-right: -40px;">Туда</h5>
                                    <div class="form-group">
                                        <div class="form-control">{{ element.from_is_time }}</div>
                                        <div class="form-control">{{ element.from_is }}</div>
                                    </div>

                                    <div class="form-group" style="text-align: center">
                                         <div style="padding: 5px;">Продолжительность</div>
                                         <div style="padding: 5px;">{{ element.duration }}</div>
                                    </div>

                                    <div class="form-group">
                                        <div class="form-control">{{ element.where_is_time }}</div>
                                        <div class="form-control">{{ element.where }}</div>
                                    </div>



                                    <h5 style="margin-top: -36px;
                                    margin-left: 120px;
                                    margin-right: -81px;">Обратно</h5>
                                <div class="form-group">
                                        <div class="form-control">{{ element.back_from_is_time }}</div>
                                        <div class="form-control">{{ element.back_from_is }}</div>
                                    </div>

                                    <div class="form-group" style="text-align: center">
                                         <div style="padding: 5px;">Продолжительность</div>
                                         <div style="padding: 5px;">{{ element.back_duration }}</div>
                                    </div>

                                    <div class="form-group">
                                        <div class="form-control">{{ element.back_where_is_time }}</div>
                                        <div class="form-control">{{ element.back_where }}</div>
                                    </div>


                                        <div class="form-group">
                                        <button type="submit" class="btn btn-warning" id="{{ element.id}}_btn"
                                             style="margin-top: 16px;
                                             margin-left: 20px;">Возврат</button>
                                                    </div>
                    </div>
                    <hr>
               {% endfor %}
           {% endif %}
           </div>
        </div>
    </div>

    <div id="ErrorContent"></div>

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>


    <script>

      $(document).on("click", function(e){
          if ($(e.target)[0].outerText === 'Возврат'){

              $('#ErrorContent').empty();

              let id = $(e.target).attr("id").slice(0,-4)

                  $.ajax (
                   {
                       url: 'delete_ticket/',
                       type: 'GET',
                       data: {
                          'id': id,
                      },
                      success: function (id) {
                           id = $(e.target).attr("id")
                           let btn = $(`#${id}`)
                           btn.removeClass('btn btn-warning')
                           .addClass('btn btn-secondary')
                           .css({'pointer-events' : 'none'});
                      },
                      error: function (error) {
                           $("#ErrorContent").append(error)
                      },
                      complete: function(data) {

                      }
                    })
                }
            })
  </script>

    </body>
</html>

project/templates/avia/search.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
            integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
            crossorigin="anonymous"
    >

    <title>avia-reis</title>

    <style>
        html, body {
            height: 100%;
        }
        body {
            background-color: #6EA1FF;
        }
        p{
            padding: 7px;
        }
        .nav-tabs .nav-link {
            border: 0;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }
        .form-group {
            margin-bottom: 6rem;
        }
        .mb-4, .my-4 {
            margin-bottom: 6.5rem!important;
        }
         hr {
            border: none; /* Убираем границу */
            background-color: #5C5C5C; /* Цвет линии */
            color: #5C5C5C; /* Цвет линии для IE6-7 */
            height: 2px;
            margin-bottom: 120px;
           }
           .disable_search{
           display: None;
           }
    </style>
  </head>
  <body>



    <div id="Search" class="disable_search"
        style="
        position: absolute;
        width: 100%;
        height: 100%;
        background: black;
        z-index: 99;
        opacity: .9;
           "></div>

        <div class="spinner-border disable_search" role="status" id="Loader" style="
        z-index: 999;
        position: absolute;
        color: white;
        margin-top: 400px;
        margin-left: 47%;
        ">
            <span class="sr-only"></span>
        </div>




    <ul class="nav nav-tabs d-flex justify-content-center align-items-center" style="background: white">
          <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/root/">Главная</a>
          </li>
          <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/">Поиск авиобилетов</a>
          </li>
          <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/list_buy_ticket/">Мои авиобилеты</a>
          </li>
    </ul>



    <div class="container-fluid d-flex h-50 justify-content-center align-items-center">
        <div class="row bg-white shadow-sm" style="border-radius: 5px">
           <div class="col p-3" style="background: #F3F3F3; border-radius: 5px">
            <h3 class="text-center mb-3">Поиск авиабилетов</h3>
               <form class="form-inline" id="AviaSearch">
                  <div class="form-group">
                    {{ form.as_p }}
                  </div>
                   <button type="submit" class="btn btn-warning">Найти билет</button>
                </form>
           </div>
        </div>
    </div>

    <div id="AviaReisContent"></div>
    <div id="ErrorContent"></div>




    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>


    <script>
      $(document).ready(function () {
          $('#AviaSearch').submit(function (e) {
               e.preventDefault()

              $('#AviaReisContent').empty();
              $('#ErrorContent').empty();

              var from_is = $('#id_from_is').val()
              var where = $('#id_where').val()
              var when = $('#id_when').val()
              var back = $('#id_back').val()
              var passengers = $('#id_passengers').val()
              var classe = $('#id_classe').val()



              $('#Search').removeClass('disable_search')
              $('#Loader').removeClass('disable_search')

               $.ajax (
                   {
                       url: 'list_reis/',
                       type: 'GET',
                       data: {
                          'from_is': from_is,
                          'where': where,
                          'when': when,
                          'back': back,
                          'passengers': passengers,
                          'classe': classe,
                      },
                      success: function (html) {
                          if (html['error']){
                              $("#AviaReisContent").append(html['error'])
                          }
                          else{
                              $("#AviaReisContent").append(html)
                          }
                      },
                      error: function (error) {
                          $("#ErrorContent").append(error)
                      },
                      complete: function(data) {
                          $('#Search').addClass('disable_search')
                          $('#Loader').addClass('disable_search')
                      }
                    })
          });
      })

      $(document).on("click", function(e){
          if ($(e.target)[0].outerText === 'Купить'){

              let id = $(e.target).attr("id").slice(0,-4)
              let form = $(`#${id}`)[0].children
              let form_data = [];

              $.each(form,function(key,data) {
                  for (let i = 0; i < data?.textContent.trim().split("\n").length; i++) {
                      form_data.push({
                       key : data?.textContent.trim().split("\n")[i]
                      })
                  }
              });

                  $.ajax (
                   {
                       url: 'buy_ticket/',
                       type: 'GET',
                       data: {
                          'form_data': form_data,
                      },
                      success: function (id) {
                           id = $(e.target).attr("id")
                           let btn = $(`#${id}`)
                           btn.removeClass('btn btn-warning')
                           .addClass('btn btn-secondary')
                           .css({'pointer-events' : 'none'});
                      },
                      error: function (error) {
                      },
                      complete: function(data) {

                      }
                    })
                }
            })
  </script>


  </body>
</html>

project/templates/buy_ticket/ticket_list.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
            integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
            crossorigin="anonymous"
    >

    <title>avia-reis</title>

    <style>
        html, body {
            height: 100%;
        }
        body {
            background-color: #6EA1FF;
        }
        p{
            padding: 7px;
        }
        .nav-tabs .nav-link {
            border: 0;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }
        .form-group {
            margin-bottom: 6rem;
        }
        .mb-4, .my-4 {
            margin-bottom: 6.5rem!important;
        }
         hr {
            border: none; /* Убираем границу */
            background-color: #5C5C5C; /* Цвет линии */
            color: #5C5C5C; /* Цвет линии для IE6-7 */
            height: 2px;
            margin-bottom: 120px;
           }
    </style>
  </head>
  <body>


    <ul class="nav nav-tabs d-flex justify-content-center align-items-center" style="background: white">
          <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/root/">Главная</a>
          </li>
          <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/">Поиск авиобилетов</a>
          </li>
          <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/list_buy_ticket/">Мои авиобилеты</a>
          </li>
    </ul>

   <div class="container-fluid d-flex justify-content-center align-items-center">
        <div class="bg-white shadow-sm" style="border-radius: 5px; margin-top: 100px;">
           <div class="col p-3" style="background: #F3F3F3; border-radius: 5px">
            <h3 class="text-center mb-4" style="margin-bottom: 10px;">Мои билеты</h3>
           {% if not ticket_list.count %}
              <p style="text-align: center"> У вас нет билетов</p>
           {% else %}
                {% for element in ticket_list %}
                    <div class="form-group form-row" style="margin: 30px;" id="{{ element.id }}">


                                <h5 style="margin-top: -40px;; margin-right: -40px;">Туда</h5>
                                    <div class="form-group">
                                        <div class="form-control">{{ element.from_is_time }}</div>
                                        <div class="form-control">{{ element.from_is }}</div>
                                    </div>

                                    <div class="form-group" style="text-align: center">
                                         <div style="padding: 5px;">Продолжительность</div>
                                         <div style="padding: 5px;">{{ element.duration }}</div>
                                    </div>

                                    <div class="form-group">
                                        <div class="form-control">{{ element.where_is_time }}</div>
                                        <div class="form-control">{{ element.where }}</div>
                                    </div>



                                    <h5 style="margin-top: -36px;
                                    margin-left: 120px;
                                    margin-right: -81px;">Обратно</h5>
                                <div class="form-group">
                                        <div class="form-control">{{ element.back_from_is_time }}</div>
                                        <div class="form-control">{{ element.back_from_is }}</div>
                                    </div>

                                    <div class="form-group" style="text-align: center">
                                         <div style="padding: 5px;">Продолжительность</div>
                                         <div style="padding: 5px;">{{ element.back_duration }}</div>
                                    </div>

                                    <div class="form-group">
                                        <div class="form-control">{{ element.back_where_is_time }}</div>
                                        <div class="form-control">{{ element.back_where }}</div>
                                    </div>


                                        <div class="form-group">
                                        <button type="submit" class="btn btn-warning" id="{{ element.id}}_btn"
                                             style="margin-top: 16px;
                                             margin-left: 20px;">Возврат</button>
                                                    </div>
                    </div>
                    <hr>
               {% endfor %}
           {% endif %}
           </div>
        </div>
    </div>

    <div id="ErrorContent"></div>

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>


    <script>

      $(document).on("click", function(e){
          if ($(e.target)[0].outerText === 'Возврат'){

              $('#ErrorContent').empty();

              let id = $(e.target).attr("id").slice(0,-4)

                  $.ajax (
                   {
                       url: 'delete_ticket/',
                       type: 'GET',
                       data: {
                          'id': id,
                      },
                      success: function (id) {
                           id = $(e.target).attr("id")
                           let btn = $(`#${id}`)
                           btn.removeClass('btn btn-warning')
                           .addClass('btn btn-secondary')
                           .css({'pointer-events' : 'none'});
                      },
                      error: function (error) {
                           $("#ErrorContent").append(error)
                      },
                      complete: function(data) {

                      }
                    })
                }
            })
  </script>

    </body>
</html>